let placesToVisit: string[] = ["Bilal", "Haris", "Wali", "Qasim","Sami"];
console.log("Original Order:");
console.log(placesToVisit);
console.log("\nAlphabetical Order:");
console.log([...placesToVisit].sort());
console.log("\nOrignal order (unchanged):");
console.log(placesToVisit);
console.log("\nRevers Alphabetical Oerder:");
console.log([...placesToVisit].sort().reverse());
console.log("\nOrignal Order (unchanged):");
console.log(placesToVisit);
console.log("\nReversed Order:");
placesToVisit.reverse();
console.log(placesToVisit);
console.log("\nReversed Again (back to original order)");
placesToVisit.reverse();
console.log(placesToVisit);
console.log("\nSorted Alphabetically:");
console.log(placesToVisit.sort());
console.log("\nSorted in Reverse Alphabetical order:");
console.log(placesToVisit.sort().reverse());
